### ISSUE TITLE
create project2

### ISSUE THREAD

**Issue by albeechen** [albeechen/schola-demo#1]
create restful api - get. post. put. delete

**Comment by chunyenHuang** [comment]
### First
Save your npm dependency to `package.json `
```
npm i express --save
```
Add [`.gitignore`](https://git-scm.com/docs/gitignore)

----

### Syntax
1. Use single quote in *.js and double quote in *.json. You can move `newStudent template to a separate json file 
2. Use { } all time (if statement...)
3. Use es6 function
```
const functionName = (arguments) => { };
```
----
### Middleware
should return res instead of err;
```
serverApp.use('/', (req, res, next) => {
	fs.readFile(filePath, 'utf8', (err, data) => {
		if (err) return res.send(err);

                // also put your data into request properties instead of using global variable
		req.studentDatas = JSON.parse( data );
		next();
	});
});
```
---
### CRUD
You already have a middleware to get all student datas, you may also need another middleware to get the student data by `request.params.id`.
This middleware should be placed before 
1. GET `/:id`
2. PUT `/:id`
3. POST `/:id`
4. DELETE `/:id`

This middleware should return res.send(err) when the `request.params.id` has no match. 
Trust me this will save your time.  

Besides, you will need to take a look of [Array Prototypes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array). In your codes, matching data is relied on the index number, which will result an issue.  

For routes with params, should only return the request entity not all datas~

----
### POST
1. Use [body parser](https://www.npmjs.com/package/body-parser) for request.body 
2. _id/id should generate by server based on the current datas;
3. function saveFile should have a callback for res.send(), you can ignore the error for writeFile
----
### Routes
You may rename the route from `/id/:id` to `/student/:id` which makes more sense for general users.

**Comment by chunyenHuang** [comment]
you may use the following method to commit your changes, `#1` is this issue, so I can follow up.
```
git commit -m "your changes log  #1"  
```

**Comment by albeechen** [comment]
done with "npm i express --save" and add .gitignore

**Comment by chunyenHuang** [comment]
lol 我是說 你commit的時候在 commit message裡面加入 #1, github自己會幫你把code放進來這裡... 就不用手動來回覆了，我看commit就可以了

**Comment by chunyenHuang** [comment]
great. you may close this issue.

I hope that you learn something about using common callback functions and middlewares.
